import { adminController } from '../controllers/admin.controller.js'
import { requireAdminAuth } from '../middlewares/auth.middleware.js'
import { requireRole } from '../middlewares/role.middleware.js'

export async function adminRoutes(app) {
  app.addHook('preHandler', requireAdminAuth)
  app.addHook('preHandler', requireRole('admin'))
  app.get('/dashboard', adminController.dashboard)
  app.get('/products', adminController.products)
  app.get('/products/:id', adminController.product)
  app.post('/products', adminController.createProduct)
  app.patch('/products/:id', adminController.updateProduct)
  app.delete('/products/:id', adminController.deleteProduct)
  app.get('/categories', adminController.categories)
  app.post('/categories', adminController.createCategory)
  app.patch('/categories/:id', adminController.updateCategory)
  app.get('/categories/:id/delete-impact', adminController.categoryDeleteImpact)
  app.delete('/categories/:id', adminController.deleteCategory)
  app.get('/colors', adminController.colors)
  app.post('/colors', adminController.createColor)
  app.patch('/colors/:id', adminController.updateColor)
  app.delete('/colors/:id', adminController.deleteColor)
  app.get('/sizes', adminController.sizes)
  app.post('/sizes', adminController.createSize)
  app.patch('/sizes/:id', adminController.updateSize)
  app.delete('/sizes/:id', adminController.deleteSize)
  app.get('/hero-banners', adminController.heroBanners)
  app.post('/hero-banners', adminController.createHeroBanner)
  app.patch('/hero-banners/:id', adminController.updateHeroBanner)
  app.delete('/hero-banners/:id', adminController.deleteHeroBanner)
  app.get('/users', adminController.users)
  app.patch('/users/:id', adminController.updateUser)
  app.get('/orders/export/csv', adminController.exportOrdersCsv)
  app.get('/orders', adminController.orders)
  app.get('/orders/:id', adminController.order)
  app.patch('/orders/bulk', adminController.bulkUpdateOrders)
  app.patch('/orders/:id', adminController.updateOrder)
  app.get('/subscriptions', adminController.subscriptions)
  app.post('/subscriptions', adminController.createSubscription)
  app.patch('/subscriptions/:id', adminController.updateSubscription)
  app.delete('/subscriptions/:id', adminController.deleteSubscription)
  app.get('/coupons', adminController.coupons)
  app.post('/coupons', adminController.createCoupon)
  app.patch('/coupons/:id', adminController.updateCoupon)
  app.delete('/coupons/:id', adminController.deleteCoupon)
  app.get('/settings', adminController.settings)
  app.put('/settings/footer-marquee', adminController.updateFooterMarquee)
  app.put('/settings/announcement-bar', adminController.updateAnnouncementBar)
  app.put('/settings/branding', adminController.updateBranding)
  app.put('/settings/theme', adminController.updateTheme)
}
